// frontend/src/components/ui/input.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        "file:text-foreground placeholder:text-slate-400 selection:bg-emerald-100 selection:text-slate-900 border-slate-300 h-9 w-full min-w-0 rounded-md border bg-white px-3 py-1 text-base text-slate-900 shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
        "focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",
        "aria-invalid:ring-destructive/20 aria-invalid:border-destructive",
        className
      )}
      {...props}
    />
  )
}

export { Input }

// frontend/src/lib/components/ui/Input.svelte
<script lang="ts">
	import { cn } from '$lib/utils';

	let {
		class: className = '',
		type = 'text',
		value = $bindable(''),
		...rest
	} = $props();
</script>

<input
	type={type}
	data-slot="input"
	class={cn(
		'file:text-foreground placeholder:text-slate-400 selection:bg-emerald-100 selection:text-slate-900 border-slate-300 h-9 w-full min-w-0 rounded-md border bg-white px-3 py-1 text-base text-slate-900 shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm',
		'focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]',
		'aria-invalid:ring-destructive/20 aria-invalid:border-destructive',
		className
	)}
	bind:value
	{...rest}
/>
