// frontend/src/routes/recovery/+page.svelte
<script lang="ts">
	import { Library } from 'lucide-svelte';
	import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle } from '$lib/components/ui';
</script>

<svelte:head>
	<title>Account Recovery - Bayt al Hikmah</title>
</svelte:head>

<div class="flex min-h-screen items-center justify-center bg-gradient-to-b from-slate-50 to-slate-100 px-4">
	<div class="w-full max-w-md">
		<div class="mb-8 flex flex-col items-center">
			<div class="mb-4 rounded-xl bg-emerald-600 p-3"><Library class="h-8 w-8 text-white" /></div>
			<h1 class="text-3xl font-bold text-slate-900">Bayt al Hikmah</h1>
		</div>

		<Card>
			<CardHeader class="text-center">
				<CardTitle>Account Recovery</CardTitle>
				<CardDescription>Password recovery is not implemented yet.</CardDescription>
			</CardHeader>
			<CardContent>
				<a href="/login"><Button class="w-full">Back to Sign In</Button></a>
			</CardContent>
		</Card>
	</div>
</div>

// frontend/app/routes/recovery.tsx
import { Library } from "lucide-react";
import { Link } from "react-router";
import { Button } from "~/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "~/components/ui/card";

export default function RecoveryPage() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-gradient-to-b from-slate-50 to-slate-100 px-4">
      <div className="w-full max-w-md">
        <div className="mb-8 flex flex-col items-center">
          <div className="mb-4 rounded-xl bg-emerald-600 p-3">
            <Library className="h-8 w-8 text-white" />
          </div>
          <h1 className="text-3xl font-bold text-slate-900">Bayt al Hikmah</h1>
        </div>
        <Card>
          <CardHeader className="text-center">
            <CardTitle>Account Recovery</CardTitle>
            <CardDescription>Password recovery is not implemented yet.</CardDescription>
          </CardHeader>
          <CardContent>
            <Link to="/login">
              <Button className="w-full">Back to Sign In</Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
